
import type {NumericEnumInterface} from "@/public/js/common/type";

export const  GENDER: NumericEnumInterface = {
    NOT_SPECIFIED : 0,
    MALE : 100,
    FEMALE : 200,
}

export const  MARITAL_STATUS: NumericEnumInterface = {
    NOT_SPECIFIED : 0,
    SINGLE : 100,
    MARRIED : 200,
    WIDOWED : 201,
    DIVORCED : 202,
    SEPARATED : 203,
}

export const  EMPLOYEE_USER_CREATION: NumericEnumInterface = {
    NONE : 0,
    AUTOGENERATED : 1,
    EXISTING_USER : 2,
    MANUAL : 3,
}