
export const  GENDER = {
    NOT_SPECIFIED : 0,
    MALE : 1,
    FEMALE : 2,
}

export const  MARITAL_STATUS = {
    NOT_SPECIFIED : 0,
    SINGLE : 1,
    MARRIED : 2,
    WIDOWED : 3,
    DIVORCED : 4,
    SEPARATED : 5,
}

export const  EMPLOYEE_USER_CREATION = {
    NONE : 0,
    AUTOGENERATED : 1,
    EXISTING_USER : 2,
    MANUAL : 3,
}