
import type {NumericEnumInterface, StringEnumInterface} from "@/public/js/common/type";

export const  GENDER: NumericEnumInterface = {
    NOT_SPECIFIED : 0,
    MALE : 100,
    FEMALE : 200,
}

export const  MARITAL_STATUS: NumericEnumInterface = {
    NOT_SPECIFIED : 0,
    SINGLE : 100,
    MARRIED : 200,
    WIDOWED : 201,
    DIVORCED : 202,
    SEPARATED : 203,
}

export const  EMPLOYEE_USER_CREATION: NumericEnumInterface = {
    NONE : 0,
    AUTOGENERATED : 1,
    EXISTING_USER : 2,
    MANUAL : 3,
}

export const PH_IDENTIFICATION_TYPE_HEADERS: StringEnumInterface = {
    PH_SSS : 'PH.2: SSS',
    PH_PHILHEALTH : 'PH.3: Philhealth',
    PH_PAG_IBIG : 'PH.4: Pag-IBIG',
    PH_TIN : 'PH.5: TIN',
}

export const PH_IDENTIFICATION_TYPE: StringEnumInterface = {
    PH_SSS : 'PH.2',
    PH_PHILHEALTH : 'PH.3',
    PH_PAG_IBIG : 'PH.4',
    PH_TIN : 'PH.5',
}

export const PH_IDENTIFICATION_TYPE_NAME: StringEnumInterface = {
    [PH_IDENTIFICATION_TYPE.PH_SSS as string]: 'SSS (Social Security System)',
    [PH_IDENTIFICATION_TYPE.PH_PHILHEALTH as string]: 'Philhealth (PHIC)',
    [PH_IDENTIFICATION_TYPE.PH_PAG_IBIG as string]: 'Pag-IBIG (HDMF)',
    [PH_IDENTIFICATION_TYPE.PH_TIN as string]: 'TIN',
}