
export const  EMPLOYMENT_STATUS = {
    ACTIVE : 0,
    INACTIVE : 1,
}

export const EMPLOYMENT_STATUS_NAME = {
    [EMPLOYMENT_STATUS.ACTIVE]: 'Active',
    [EMPLOYMENT_STATUS.INACTIVE]: 'Inactive',
}

export const EMPLOYMENT_TYPE = {
    OJT : 0,
    INTERN : 1,
    PROBATIONARY : 2,
    FULL_TIME : 3,
    PART_TIME : 4,
    CONTRACT : 5,
    NOT_SPECIFIED : 6,
}

export const EMPLOYMENT_TYPE_NAME = {
    [EMPLOYMENT_TYPE.OJT]: 'OJT',
    [EMPLOYMENT_TYPE.INTERN]: 'Intern',
    [EMPLOYMENT_TYPE.PROBATIONARY]: 'Probationary',
    [EMPLOYMENT_TYPE.FULL_TIME]: 'Full Time',
    [EMPLOYMENT_TYPE.PART_TIME]: 'Part Time',
    [EMPLOYMENT_TYPE.CONTRACT]: 'Contract',
    [EMPLOYMENT_TYPE.NOT_SPECIFIED]: 'Not Specified',
}

export const  END_OF_SERVICE_TYPE = {
    END_OF_CONTRACT : 0,
    RESIGNED : 1,
    TERMINATED : 2,
    RETIRED : 3,
    DEATH : 4,
    MEDICAL_SEPARATION : 5,
    DISABILITY : 6,
    NOT_SPECIFIED : 7,
}

export const END_OF_SERVICE_TYPE_NAME = {
    [END_OF_SERVICE_TYPE.END_OF_CONTRACT]: 'End of Contract',
    [END_OF_SERVICE_TYPE.RETIRED]: 'Retired',
    [END_OF_SERVICE_TYPE.TERMINATED]: 'Terminated',
    [END_OF_SERVICE_TYPE.RESIGNED]: 'Resigned',
    [END_OF_SERVICE_TYPE.DEATH]: 'Death',
    [END_OF_SERVICE_TYPE.MEDICAL_SEPARATION]: 'Medical Separation',
    [END_OF_SERVICE_TYPE.DISABILITY]: 'Disability',
    [END_OF_SERVICE_TYPE.NOT_SPECIFIED]: 'Not Specified',
}