
export const SHIFT_ASSIGNMENT_TAB = {
    LIST : 0,
    CREATE_SHIFT_ASSIGNMENTS : 1,
    MANAGE_ASSIGNED_SHIFTS : 2,
}

export const SHIFT_ASSIGNMENT_TAB_NAME = {
    [SHIFT_ASSIGNMENT_TAB.LIST]: 'List',
    [SHIFT_ASSIGNMENT_TAB.CREATE_SHIFT_ASSIGNMENTS]: 'Create Shift Assignments',
    [SHIFT_ASSIGNMENT_TAB.MANAGE_ASSIGNED_SHIFTS]: 'Manage Assigned Shifts',
}